import textwrap
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate, CondPageBreak, Frame, HRFlowable, PageBreak, PageTemplate,
    Paragraph, Preformatted, Spacer, Table, TableStyle,
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.barcharts import HorizontalBarChart

from checks.runner import Finding, Severity, Status


SEV_COLOUR = {
    Severity.CRITICAL: colors.HexColor("#b91c1c"),
    Severity.HIGH:     colors.HexColor("#ea580c"),
    Severity.MEDIUM:   colors.HexColor("#ca8a04"),
    Severity.LOW:      colors.HexColor("#2563eb"),
    Severity.INFO:     colors.HexColor("#475569"),
}

STATUS_COLOUR = {
    Status.PASS:  colors.HexColor("#16a34a"),
    Status.FAIL:  colors.HexColor("#b91c1c"),
    Status.WARN:  colors.HexColor("#ca8a04"),
    Status.INFO:  colors.HexColor("#475569"),
    Status.ERROR: colors.HexColor("#6b21a8"),
}

PRIMARY = colors.HexColor("#0f172a")
ACCENT  = colors.HexColor("#1d4ed8")
BG_SOFT = colors.HexColor("#f1f5f9")
BORDER  = colors.HexColor("#cbd5e1")
MUTED   = colors.HexColor("#64748b")
DIVIDER = colors.HexColor("#e2e8f0")


def _styles():
    base = getSampleStyleSheet()
    s = {
        "title":    ParagraphStyle("title", parent=base["Title"], fontSize=26, leading=30, textColor=PRIMARY, alignment=TA_LEFT, spaceAfter=4),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontSize=12, leading=16, textColor=colors.HexColor("#475569"), spaceAfter=14),
        "h1":       ParagraphStyle("h1", parent=base["Heading1"], fontSize=18, leading=22, textColor=PRIMARY, spaceBefore=18, spaceAfter=8),
        "h2":       ParagraphStyle("h2", parent=base["Heading2"], fontSize=13, leading=17, textColor=ACCENT, spaceBefore=14, spaceAfter=6),
        "body":     ParagraphStyle("body", parent=base["BodyText"], fontSize=10, leading=14, textColor=PRIMARY),
        "small":    ParagraphStyle("small", parent=base["BodyText"], fontSize=9, leading=12, textColor=colors.HexColor("#334155")),
        # Finding header (used inside the header card table cell — no own spacing).
        "finding_h":    ParagraphStyle("finding_h", parent=base["Heading3"], fontSize=11.5, leading=14, textColor=PRIMARY, spaceBefore=0, spaceAfter=0),
        # Body copy inside a finding — consistent left indent aligns with the
        # header card's coloured rail so the whole block reads as one unit.
        "finding_body": ParagraphStyle("finding_body", parent=base["BodyText"], fontSize=10, leading=14, textColor=PRIMARY, leftIndent=14, rightIndent=10, spaceBefore=4, spaceAfter=2),
        # Small uppercase caption (EVIDENCE / REMEDIATION) — subdued so it
        # structures the block without competing with the content.
        "finding_label": ParagraphStyle("finding_label", parent=base["BodyText"], fontName="Helvetica-Bold", fontSize=7.5, leading=10, textColor=MUTED, leftIndent=14, spaceBefore=10, spaceAfter=3),
        # Evidence code block — soft background, thin border, indented text
        # to match the rest of the finding body.
        "mono":         ParagraphStyle("mono", parent=base["Code"], fontName="Courier", fontSize=7.8, leading=10.5, textColor=colors.HexColor("#0f172a"), backColor=BG_SOFT, borderColor=BORDER, borderWidth=0.5, borderPadding=7, leftIndent=14, rightIndent=10, spaceBefore=0, spaceAfter=4, wordWrap=None),
        "cover_big":    ParagraphStyle("coverbig", parent=base["Title"], fontSize=42, leading=48, textColor=colors.white, alignment=TA_LEFT),
        "cover_sub":    ParagraphStyle("coversub", parent=base["Normal"], fontSize=14, leading=18, textColor=colors.HexColor("#cbd5e1"), alignment=TA_LEFT),
        # Category band (full-width dark header that introduces a section).
        "cat_title":    ParagraphStyle("cat_title", fontName="Helvetica-Bold", fontSize=14, leading=18, textColor=colors.white),
        "cat_count":    ParagraphStyle("cat_count", fontName="Helvetica", fontSize=9.5, leading=14, textColor=colors.HexColor("#cbd5e1"), alignment=TA_RIGHT),
    }
    return s


def _page_background(canvas, doc):
    canvas.saveState()
    w, h = A4
    # header bar
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, h - 18 * mm, w, 18 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(18 * mm, h - 12 * mm, "Bastion Security Audit")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(w - 18 * mm, h - 12 * mm, datetime.now().strftime("%Y-%m-%d %H:%M"))

    # footer
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(18 * mm, 10 * mm, "Generated by Bastion")
    canvas.drawRightString(w - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(18 * mm, 14 * mm, w - 18 * mm, 14 * mm)
    canvas.restoreState()


def _cover_page(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, 0, w, h, fill=1, stroke=0)

    canvas.setFillColor(ACCENT)
    canvas.rect(0, h - 170 * mm, w, 6 * mm, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 52)
    canvas.drawString(22 * mm, h - 70 * mm, "Bastion")
    canvas.setFont("Helvetica", 18)
    canvas.setFillColor(colors.HexColor("#cbd5e1"))
    canvas.drawString(22 * mm, h - 82 * mm, "Windows Security Audit Report")

    canvas.setFont("Helvetica", 11)
    canvas.drawString(22 * mm, 40 * mm, f"Generated: {datetime.now().strftime('%A %d %B %Y, %H:%M')}")
    canvas.drawString(22 * mm, 34 * mm, "Classification: Confidential — restricted to system owner")
    canvas.restoreState()


def _severity_pill(sev: Severity):
    d = Drawing(55, 14)
    d.add(Rect(0, 0, 55, 14, rx=3, ry=3, fillColor=SEV_COLOUR[sev], strokeColor=SEV_COLOUR[sev]))
    d.add(String(27.5, 4, sev.value, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=8, textAnchor="middle"))
    return d


def _status_pill(status: Status):
    label = status.value
    d = Drawing(40, 14)
    d.add(Rect(0, 0, 40, 14, rx=3, ry=3, fillColor=STATUS_COLOUR[status], strokeColor=STATUS_COLOUR[status]))
    d.add(String(20, 4, label, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=8, textAnchor="middle"))
    return d


def _severity_bar_chart(counts: dict):
    order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    data = [[counts.get(s, 0) for s in order]]
    d = Drawing(460, 150)
    chart = HorizontalBarChart()
    chart.x = 90
    chart.y = 20
    chart.height = 110
    chart.width = 340
    chart.data = data
    chart.categoryAxis.categoryNames = [s.value for s in order]
    chart.categoryAxis.labels.fontName = "Helvetica-Bold"
    chart.categoryAxis.labels.fontSize = 9
    chart.valueAxis.valueMin = 0
    max_v = max(data[0] + [1])
    chart.valueAxis.valueMax = max_v + max(1, max_v // 4)
    chart.valueAxis.valueStep = max(1, (chart.valueAxis.valueMax) // 5)
    chart.barWidth = 14
    chart.groupSpacing = 8
    chart.bars[0].fillColor = ACCENT
    for i, s in enumerate(order):
        chart.bars[(0, i)].fillColor = SEV_COLOUR[s]
    d.add(chart)
    return d


def _category_band(title: str, num_findings: int, styles):
    """Full-width dark band that introduces a new category section.

    Gives each category a clear visual boundary so findings read as a grouped
    set instead of floating in a sea of white.
    """
    count_word = "finding" if num_findings == 1 else "findings"
    tbl = Table(
        [[
            Paragraph(_escape(title), styles["cat_title"]),
            Paragraph(f"{num_findings} {count_word}", styles["cat_count"]),
        ]],
        colWidths=[None, 90],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PRIMARY),
        ("LINEBELOW",  (0, 0), (-1, -1), 3, ACCENT),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
        ("TOPPADDING",    (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    return tbl


def _finding_block(finding: Finding, styles, is_last: bool = False):
    """Render a finding as a grouped card.

    Layout:
      [ ▌ Finding name                          SEV   STATUS ]   <- header card
          Description paragraph (indented to align with rail) .
          EVIDENCE                                              <- small caption
          [ code block with soft background + border           ]
          REMEDIATION
          Remediation paragraph .
      ─────────────────────────────────────────────────────────   <- divider

    The header card is a small Table (safe — always fits on a page). All body
    content below the header is a flat sequence of flowables with a consistent
    ``leftIndent`` so everything aligns to the rail without needing nested
    tables. This matters because a single table cell cannot split across pages
    in reportlab, and evidence blocks routinely run to 200+ lines.
    """
    colour = SEV_COLOUR[finding.severity] if finding.status in (Status.FAIL, Status.WARN, Status.ERROR) else STATUS_COLOUR[finding.status]

    # Header card — colored left rail, name on the left, severity + status
    # pills on the right. Always bounded, so Table is safe here.
    header_tbl = Table(
        [[
            Paragraph(f"<b>{_escape(finding.name)}</b>", styles["finding_h"]),
            _severity_pill(finding.severity),
            _status_pill(finding.status),
        ]],
        colWidths=[None, 58, 46],
    )
    header_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), colors.white),
        ("BOX",           (0, 0), (-1, -1), 0.5, BORDER),
        ("LINEBEFORE",    (0, 0), (0, -1), 4, colour),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (0, -1), 12),
        ("LEFTPADDING",   (1, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-2, -1), 6),
        ("RIGHTPADDING",  (-1, 0), (-1, -1), 12),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    out = [CondPageBreak(80), header_tbl]

    if finding.description:
        out.append(Paragraph(_escape(finding.description), styles["finding_body"]))

    if finding.evidence:
        out.append(Paragraph("EVIDENCE", styles["finding_label"]))
        # Standalone Preformatted — can split across pages. Do NOT wrap in a
        # table (see docstring).
        out.append(Preformatted(_wrap_evidence(finding.evidence), styles["mono"]))

    if finding.recommendation:
        out.append(Paragraph("REMEDIATION", styles["finding_label"]))
        out.append(Paragraph(_escape(finding.recommendation), styles["finding_body"]))

    # Breathing room + a hairline divider between findings so they don't blur
    # together. Skip the divider after the last finding in a category — the
    # next category band provides a stronger break.
    out.append(Spacer(1, 10))
    if not is_last:
        out.append(HRFlowable(width="100%", thickness=0.4, color=DIVIDER,
                              spaceBefore=0, spaceAfter=12))
    return out


def _escape(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _wrap_evidence(text: str, width: int = 95, max_lines: int = 250) -> str:
    """Pre-wrap monospace evidence for the PDF.

    - Breaks long lines at `width` characters (hard-breaks tokens without
      whitespace so registry paths and URLs never run off the page).
    - Caps the total rendered lines at `max_lines`; the full untruncated
      output is still in findings.json and scan.log. This prevents a single
      cell from being taller than an A4 page (reportlab refuses to split a
      single cell across pages and raises LayoutError).
    """
    out = []
    for raw in (text or "").splitlines() or [""]:
        raw = raw.rstrip()
        if len(raw) <= width:
            out.append(raw)
            continue
        wrapped = textwrap.wrap(
            raw,
            width=width,
            break_long_words=True,
            break_on_hyphens=False,
            drop_whitespace=False,
            replace_whitespace=False,
            tabsize=4,
        )
        if not wrapped:
            for i in range(0, len(raw), width):
                out.append(raw[i:i + width])
        else:
            out.extend(wrapped)

    if len(out) > max_lines:
        omitted = len(out) - max_lines
        out = out[:max_lines]
        out.append(f"... [truncated {omitted} more lines — see scan.log / findings.json for the full output]")
    return "\n".join(out)


def build_report(results: list[tuple[str, list[Finding]]], host: str, output_path: Path):
    styles = _styles()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = BaseDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=20 * mm,
        title=f"Bastion — {host}",
        author="Bastion",
    )

    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="normal",
    )
    cover_frame = Frame(0, 0, A4[0], A4[1], id="cover", leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)

    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[cover_frame], onPage=_cover_page),
        PageTemplate(id="normal", frames=[frame], onPage=_page_background),
    ])

    story = []

    # cover placeholder; actual render happens in onPage
    story.append(PageBreak())
    story[-1].nextTemplate = "normal"

    # executive summary
    all_findings = [f for _, lst in results for f in lst]
    sev_counts = {s: 0 for s in Severity}
    stat_counts = {s: 0 for s in Status}
    for f in all_findings:
        sev_counts[f.severity] += 1
        stat_counts[f.status] += 1

    total = len(all_findings)
    fails = stat_counts[Status.FAIL] + stat_counts[Status.WARN] + stat_counts[Status.ERROR]
    risk_level, risk_colour = _risk_rating(sev_counts)

    story.append(Paragraph("Executive Summary", styles["title"]))
    story.append(Paragraph(f"Host: <b>{_escape(host)}</b>", styles["subtitle"]))

    tbl = Table(
        [
            ["Overall Risk", "Total Checks", "Issues Found", "Critical", "High", "Medium", "Low"],
            [
                _risk_pill(risk_level, risk_colour),
                str(total),
                str(fails),
                str(sev_counts[Severity.CRITICAL]),
                str(sev_counts[Severity.HIGH]),
                str(sev_counts[Severity.MEDIUM]),
                str(sev_counts[Severity.LOW]),
            ],
        ],
        colWidths=[90, 70, 70, 50, 50, 60, 50],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, 1), 14),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("BACKGROUND", (1, 1), (-1, 1), BG_SOFT),
        ("TEXTCOLOR", (3, 1), (3, 1), SEV_COLOUR[Severity.CRITICAL]),
        ("TEXTCOLOR", (4, 1), (4, 1), SEV_COLOUR[Severity.HIGH]),
        ("TEXTCOLOR", (5, 1), (5, 1), SEV_COLOUR[Severity.MEDIUM]),
        ("TEXTCOLOR", (6, 1), (6, 1), SEV_COLOUR[Severity.LOW]),
        ("ROWBACKGROUNDS", (0, 1), (0, 1), [colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 18))

    story.append(Paragraph("Findings by Severity", styles["h2"]))
    story.append(_severity_bar_chart(sev_counts))
    story.append(Spacer(1, 12))

    # top issues summary
    critical_and_high = [f for f in all_findings if f.severity in (Severity.CRITICAL, Severity.HIGH) and f.status in (Status.FAIL, Status.WARN, Status.ERROR)]
    if critical_and_high:
        story.append(Paragraph("Priority Issues", styles["h2"]))
        rows = [["#", "Severity", "Finding"]]
        for i, f in enumerate(critical_and_high[:15], 1):
            rows.append([str(i), f.severity.value, _escape(f.name)[:90]])
        t = Table(rows, colWidths=[20, 70, None])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_SOFT]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        for i, f in enumerate(critical_and_high[:15], 1):
            t.setStyle(TableStyle([("TEXTCOLOR", (1, i), (1, i), SEV_COLOUR[f.severity]), ("FONTNAME", (1, i), (1, i), "Helvetica-Bold")]))
        story.append(t)

    story.append(PageBreak())

    # detailed findings
    story.append(Paragraph("Detailed Findings", styles["title"]))
    story.append(Paragraph("Each section groups the checks performed in that category. Findings are ordered with the most severe first.", styles["subtitle"]))

    for category, findings in results:
        if not findings:
            continue
        sorted_findings = sorted(
            findings,
            key=lambda f: (_sev_rank(f.severity), _status_rank(f.status)),
        )
        # Keep the category band with the first finding so a section never
        # starts with just a banner at the bottom of a page.
        story.append(CondPageBreak(120))
        story.append(_category_band(category, len(sorted_findings), styles))
        story.append(Spacer(1, 12))
        last_idx = len(sorted_findings) - 1
        for i, f in enumerate(sorted_findings):
            story.extend(_finding_block(f, styles, is_last=(i == last_idx)))
        story.append(Spacer(1, 14))

    doc.build(story)
    return output_path


def _sev_rank(s: Severity) -> int:
    return [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO].index(s)


def _status_rank(s: Status) -> int:
    return [Status.FAIL, Status.ERROR, Status.WARN, Status.INFO, Status.PASS].index(s)


def _risk_rating(counts):
    if counts.get(Severity.CRITICAL, 0) > 0:
        return "CRITICAL", SEV_COLOUR[Severity.CRITICAL]
    if counts.get(Severity.HIGH, 0) >= 3:
        return "HIGH", SEV_COLOUR[Severity.HIGH]
    if counts.get(Severity.HIGH, 0) > 0 or counts.get(Severity.MEDIUM, 0) >= 4:
        return "MEDIUM", SEV_COLOUR[Severity.MEDIUM]
    if counts.get(Severity.MEDIUM, 0) > 0 or counts.get(Severity.LOW, 0) > 0:
        return "LOW", SEV_COLOUR[Severity.LOW]
    return "MINIMAL", SEV_COLOUR[Severity.INFO]


def _risk_pill(label, colour):
    d = Drawing(80, 22)
    d.add(Rect(0, 0, 80, 22, rx=4, ry=4, fillColor=colour, strokeColor=colour))
    d.add(String(40, 7, label, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=11, textAnchor="middle"))
    return d
