from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph,
    Preformatted, Spacer, Table, TableStyle, KeepTogether,
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import HorizontalBarChart
from reportlab.graphics.charts.legends import Legend

from checks.runner import Finding, Severity, Status


SEV_COLOUR = {
    Severity.CRITICAL: colors.HexColor("#b91c1c"),
    Severity.HIGH:     colors.HexColor("#ea580c"),
    Severity.MEDIUM:   colors.HexColor("#ca8a04"),
    Severity.LOW:      colors.HexColor("#2563eb"),
    Severity.INFO:     colors.HexColor("#475569"),
}

STATUS_COLOUR = {
    Status.PASS:  colors.HexColor("#16a34a"),
    Status.FAIL:  colors.HexColor("#b91c1c"),
    Status.WARN:  colors.HexColor("#ca8a04"),
    Status.INFO:  colors.HexColor("#475569"),
    Status.ERROR: colors.HexColor("#6b21a8"),
}

PRIMARY = colors.HexColor("#0f172a")
ACCENT  = colors.HexColor("#1d4ed8")
BG_SOFT = colors.HexColor("#f1f5f9")
BORDER  = colors.HexColor("#cbd5e1")


def _styles():
    base = getSampleStyleSheet()
    s = {
        "title":   ParagraphStyle("title", parent=base["Title"], fontSize=26, leading=30, textColor=PRIMARY, alignment=TA_LEFT, spaceAfter=4),
        "subtitle":ParagraphStyle("subtitle", parent=base["Normal"], fontSize=12, leading=16, textColor=colors.HexColor("#475569"), spaceAfter=8),
        "h1":      ParagraphStyle("h1", parent=base["Heading1"], fontSize=18, leading=22, textColor=PRIMARY, spaceBefore=14, spaceAfter=6),
        "h2":      ParagraphStyle("h2", parent=base["Heading2"], fontSize=13, leading=17, textColor=ACCENT, spaceBefore=10, spaceAfter=4),
        "body":    ParagraphStyle("body", parent=base["BodyText"], fontSize=10, leading=14, textColor=PRIMARY),
        "small":   ParagraphStyle("small", parent=base["BodyText"], fontSize=9, leading=12, textColor=colors.HexColor("#334155")),
        "finding_h": ParagraphStyle("finding_h", parent=base["Heading3"], fontSize=12, leading=15, textColor=PRIMARY, spaceBefore=8, spaceAfter=2),
        "mono":    ParagraphStyle("mono", parent=base["Code"], fontSize=8, leading=10, textColor=colors.HexColor("#111827"), backColor=BG_SOFT, borderPadding=4, leftIndent=0, rightIndent=0),
        "cover_big": ParagraphStyle("coverbig", parent=base["Title"], fontSize=42, leading=48, textColor=colors.white, alignment=TA_LEFT),
        "cover_sub": ParagraphStyle("coversub", parent=base["Normal"], fontSize=14, leading=18, textColor=colors.HexColor("#cbd5e1"), alignment=TA_LEFT),
    }
    return s


def _page_background(canvas, doc):
    canvas.saveState()
    w, h = A4
    # header bar
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, h - 18 * mm, w, 18 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(18 * mm, h - 12 * mm, "VulnFinder Security Audit")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(w - 18 * mm, h - 12 * mm, datetime.now().strftime("%Y-%m-%d %H:%M"))

    # footer
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(18 * mm, 10 * mm, "Generated by VulnFinder")
    canvas.drawRightString(w - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(18 * mm, 14 * mm, w - 18 * mm, 14 * mm)
    canvas.restoreState()


def _cover_page(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, 0, w, h, fill=1, stroke=0)

    canvas.setFillColor(ACCENT)
    canvas.rect(0, h - 170 * mm, w, 6 * mm, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 52)
    canvas.drawString(22 * mm, h - 70 * mm, "VulnFinder")
    canvas.setFont("Helvetica", 18)
    canvas.setFillColor(colors.HexColor("#cbd5e1"))
    canvas.drawString(22 * mm, h - 82 * mm, "Windows Security Audit Report")

    canvas.setFont("Helvetica", 11)
    canvas.drawString(22 * mm, 40 * mm, f"Generated: {datetime.now().strftime('%A %d %B %Y, %H:%M')}")
    canvas.drawString(22 * mm, 34 * mm, "Classification: Confidential — restricted to system owner")
    canvas.restoreState()


def _severity_pill(sev: Severity):
    d = Drawing(55, 14)
    d.add(Rect(0, 0, 55, 14, rx=3, ry=3, fillColor=SEV_COLOUR[sev], strokeColor=SEV_COLOUR[sev]))
    d.add(String(27.5, 4, sev.value, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=8, textAnchor="middle"))
    return d


def _status_pill(status: Status):
    label = status.value
    d = Drawing(40, 14)
    d.add(Rect(0, 0, 40, 14, rx=3, ry=3, fillColor=STATUS_COLOUR[status], strokeColor=STATUS_COLOUR[status]))
    d.add(String(20, 4, label, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=8, textAnchor="middle"))
    return d


def _severity_bar_chart(counts: dict):
    order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    data = [[counts.get(s, 0) for s in order]]
    d = Drawing(460, 150)
    chart = HorizontalBarChart()
    chart.x = 90
    chart.y = 20
    chart.height = 110
    chart.width = 340
    chart.data = data
    chart.categoryAxis.categoryNames = [s.value for s in order]
    chart.categoryAxis.labels.fontName = "Helvetica-Bold"
    chart.categoryAxis.labels.fontSize = 9
    chart.valueAxis.valueMin = 0
    max_v = max(data[0] + [1])
    chart.valueAxis.valueMax = max_v + max(1, max_v // 4)
    chart.valueAxis.valueStep = max(1, (chart.valueAxis.valueMax) // 5)
    chart.barWidth = 14
    chart.groupSpacing = 8
    chart.bars[0].fillColor = ACCENT
    for i, s in enumerate(order):
        chart.bars[(0, i)].fillColor = SEV_COLOUR[s]
    d.add(chart)
    return d


def _finding_block(finding: Finding, styles):
    header_tbl = Table(
        [[Paragraph(f"<b>{_escape(finding.name)}</b>", styles["finding_h"]),
          _severity_pill(finding.severity),
          _status_pill(finding.status)]],
        colWidths=[None, 55, 45],
    )
    header_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))

    rows = []
    if finding.description:
        rows.append(Paragraph(_escape(finding.description), styles["body"]))
    if finding.evidence:
        rows.append(Paragraph("<b>Evidence</b>", styles["small"]))
        rows.append(Preformatted(finding.evidence, styles["mono"]))
    if finding.recommendation:
        rows.append(Paragraph("<b>Recommendation</b>", styles["small"]))
        rows.append(Paragraph(_escape(finding.recommendation), styles["body"]))

    inner = Table([[header_tbl]] + [[r] for r in rows], colWidths=[None])
    inner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    colour = SEV_COLOUR[finding.severity] if finding.status in (Status.FAIL, Status.WARN, Status.ERROR) else STATUS_COLOUR[finding.status]
    wrapper = Table([[inner]], colWidths=[None])
    wrapper.setStyle(TableStyle([
        ("LINEBEFORE", (0, 0), (0, -1), 4, colour),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    return KeepTogether([wrapper, Spacer(1, 6)])


def _escape(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_report(results: list[tuple[str, list[Finding]]], host: str, output_path: Path):
    styles = _styles()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = BaseDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=20 * mm,
        title=f"VulnFinder — {host}",
        author="VulnFinder",
    )

    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="normal",
    )
    cover_frame = Frame(0, 0, A4[0], A4[1], id="cover", leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)

    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[cover_frame], onPage=_cover_page),
        PageTemplate(id="normal", frames=[frame], onPage=_page_background),
    ])

    story = []

    # cover placeholder; actual render happens in onPage
    story.append(PageBreak())
    story[-1].nextTemplate = "normal"

    # executive summary
    all_findings = [f for _, lst in results for f in lst]
    sev_counts = {s: 0 for s in Severity}
    stat_counts = {s: 0 for s in Status}
    for f in all_findings:
        sev_counts[f.severity] += 1
        stat_counts[f.status] += 1

    total = len(all_findings)
    fails = stat_counts[Status.FAIL] + stat_counts[Status.WARN] + stat_counts[Status.ERROR]
    risk_level, risk_colour = _risk_rating(sev_counts)

    story.append(Paragraph("Executive Summary", styles["title"]))
    story.append(Paragraph(f"Host: <b>{_escape(host)}</b>", styles["subtitle"]))

    tbl = Table(
        [
            ["Overall Risk", "Total Checks", "Issues Found", "Critical", "High", "Medium", "Low"],
            [
                _risk_pill(risk_level, risk_colour),
                str(total),
                str(fails),
                str(sev_counts[Severity.CRITICAL]),
                str(sev_counts[Severity.HIGH]),
                str(sev_counts[Severity.MEDIUM]),
                str(sev_counts[Severity.LOW]),
            ],
        ],
        colWidths=[90, 70, 70, 50, 50, 60, 50],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, 1), 14),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("BACKGROUND", (1, 1), (-1, 1), BG_SOFT),
        ("TEXTCOLOR", (3, 1), (3, 1), SEV_COLOUR[Severity.CRITICAL]),
        ("TEXTCOLOR", (4, 1), (4, 1), SEV_COLOUR[Severity.HIGH]),
        ("TEXTCOLOR", (5, 1), (5, 1), SEV_COLOUR[Severity.MEDIUM]),
        ("TEXTCOLOR", (6, 1), (6, 1), SEV_COLOUR[Severity.LOW]),
        ("ROWBACKGROUNDS", (0, 1), (0, 1), [colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Findings by Severity", styles["h2"]))
    story.append(_severity_bar_chart(sev_counts))
    story.append(Spacer(1, 6))

    # top issues summary
    critical_and_high = [f for f in all_findings if f.severity in (Severity.CRITICAL, Severity.HIGH) and f.status in (Status.FAIL, Status.WARN, Status.ERROR)]
    if critical_and_high:
        story.append(Paragraph("Priority Issues", styles["h2"]))
        rows = [["#", "Severity", "Finding"]]
        for i, f in enumerate(critical_and_high[:15], 1):
            rows.append([str(i), f.severity.value, _escape(f.name)[:90]])
        t = Table(rows, colWidths=[20, 70, None])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_SOFT]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        for i, f in enumerate(critical_and_high[:15], 1):
            t.setStyle(TableStyle([("TEXTCOLOR", (1, i), (1, i), SEV_COLOUR[f.severity]), ("FONTNAME", (1, i), (1, i), "Helvetica-Bold")]))
        story.append(t)

    story.append(PageBreak())

    # detailed findings
    story.append(Paragraph("Detailed Findings", styles["title"]))
    story.append(Paragraph("Each section groups the checks performed in that category. Findings are ordered with the most severe first.", styles["subtitle"]))

    for category, findings in results:
        if not findings:
            continue
        story.append(Paragraph(category, styles["h1"]))
        sorted_findings = sorted(
            findings,
            key=lambda f: (_sev_rank(f.severity), _status_rank(f.status)),
        )
        for f in sorted_findings:
            story.append(_finding_block(f, styles))
        story.append(Spacer(1, 6))

    doc.build(story)
    return output_path


def _sev_rank(s: Severity) -> int:
    return [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO].index(s)


def _status_rank(s: Status) -> int:
    return [Status.FAIL, Status.ERROR, Status.WARN, Status.INFO, Status.PASS].index(s)


def _risk_rating(counts):
    if counts.get(Severity.CRITICAL, 0) > 0:
        return "CRITICAL", SEV_COLOUR[Severity.CRITICAL]
    if counts.get(Severity.HIGH, 0) >= 3:
        return "HIGH", SEV_COLOUR[Severity.HIGH]
    if counts.get(Severity.HIGH, 0) > 0 or counts.get(Severity.MEDIUM, 0) >= 4:
        return "MEDIUM", SEV_COLOUR[Severity.MEDIUM]
    if counts.get(Severity.MEDIUM, 0) > 0 or counts.get(Severity.LOW, 0) > 0:
        return "LOW", SEV_COLOUR[Severity.LOW]
    return "MINIMAL", SEV_COLOUR[Severity.INFO]


def _risk_pill(label, colour):
    d = Drawing(80, 22)
    d.add(Rect(0, 0, 80, 22, rx=4, ry=4, fillColor=colour, strokeColor=colour))
    d.add(String(40, 7, label, fillColor=colors.white, fontName="Helvetica-Bold", fontSize=11, textAnchor="middle"))
    return d
